name: fly2p
channels:
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - backcall=0.2.0=pyhd3eb1b0_0
  - ca-certificates=2025.2.25=haa95532_0
  - colorama=0.4.6=py38haa95532_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - importlib_metadata=7.0.1=hd3eb1b0_0
  - ipython=8.12.2=py38haa95532_0
  - jupyter_client=8.6.0=py38haa95532_0
  - jupyter_core=5.7.2=py38haa95532_0
  - libffi=3.4.4=hd77b12b_1
  - libsodium=1.0.18=h62dcd97_0
  - matplotlib-inline=0.1.6=py38haa95532_0
  - openssl=3.0.16=h3f729d1_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=24.2=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - python=3.8.20=h8205438_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - vc=14.42=haa95532_5
  - vs2015_runtime=14.42.34433=hbfb602d_5
  - wheel=0.44.0=py38haa95532_0
  - zeromq=4.3.5=hd77b12b_0
  - pip:
      - aiobotocore==2.22.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - alabaster==0.7.13
      - annotated-types==0.7.0
      - anyio==3.7.1
      - anywidget==0.4.2
      - app-model==0.2.8
      - appdirs==1.4.4
      - asciitree==0.3.3
      - asttokens==2.4.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - babel==2.12.1
      - bidict==0.22.1
      - botocore==1.37.3
      - build==1.0.3
      - cachecontrol==0.14.2
      - cachey==0.2.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - cleo==2.1.0
      - click==8.1.7
      - cloudpickle==2.2.1
      - comm==0.1.4
      - contourpy==1.1.0
      - crashtest==0.4.1
      - cycler==0.11.0
      - dask==2023.5.0
      - debugpy==1.8.0
      - distlib==0.3.9
      - dnspython==2.4.2
      - docstring-parser==0.15
      - docutils==0.20.1
      - dulwich==0.21.7
      - ecdsa==0.18.0
      - email-validator==2.1.0.post1
      - exceptiongroup==1.1.3
      - executing==1.2.0
      - fastapi==0.116.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - filelock==3.16.1
      - fly2p==0.2.2
      - fonttools==4.42.1
      - freetype-py==2.4.0
      - frozenlist==1.4.0
      - fsspec==2023.9.0
      - h11==0.14.0
      - h5py==3.11.0
      - heapdict==1.0.1
      - hsluv==5.0.4
      - idna==3.4
      - imageio==2.31.3
      - imagesize==1.4.1
      - imjoy==0.11.20
      - imjoy-rpc==0.5.59
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - in-n-out==0.2.1
      - installer==0.7.0
      - ipykernel==6.25.2
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.1
      - jaraco-classes==3.4.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.3.1
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.9
      - keyring==24.3.1
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - llvmlite==0.41.1
      - locket==1.0.0
      - magicgui==0.9.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - more-itertools==10.5.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - mypy-extensions==1.0.0
      - napari==0.4.19.post1
      - napari-console==0.0.9
      - napari-plugin-engine==0.2.0
      - napari-plugin-manager==0.1.4
      - napari-svg==0.1.10
      - nest-asyncio==1.5.7
      - networkx==3.1
      - npe2==0.7.9
      - numba==0.58.1
      - numcodecs==0.12.1
      - numpy==1.24.4
      - numpydoc==1.7.0
      - packaging==23.1
      - pandas==1.5.3
      - partd==1.4.0
      - pexpect==4.9.0
      - pillow==10.0.0
      - pint==0.21.1
      - pkginfo==1.12.1.2
      - pkgutil-resolve-name==1.3.10
      - pluggy==1.5.0
      - poetry==1.8.5
      - poetry-core==1.9.1
      - poetry-plugin-export==1.8.0
      - pooch==1.8.2
      - prompt-toolkit==3.0.39
      - propcache==0.2.0
      - psutil==5.9.5
      - psygnal==0.9.3
      - ptyprocess==0.7.0
      - pyasn1==0.5.0
      - pyconify==0.1.6
      - pydantic==1.10.12
      - pydantic-compat==0.1.2
      - pydantic-core==2.27.2
      - pygments==2.16.1
      - pyopengl==3.1.9
      - pyparsing==3.1.1
      - pyproject-hooks==1.0.0
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.15.0
      - python-dateutil==2.8.2
      - python-dotenv==1.0.1
      - python-engineio==4.0.0
      - python-jose==3.3.0
      - python-socketio==5.0.4
      - pytz==2023.3.post1
      - pywavelets==1.4.1
      - pywin32==306
      - pywin32-ctypes==0.2.3
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - qtconsole==5.4.4
      - qtpy==2.4.0
      - rapidfuzz==3.9.7
      - referencing==0.30.2
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rich==13.5.2
      - rpds-py==0.10.3
      - rsa==4.9
      - scanimage-tiff-reader==1.4.1.4
      - scikit-image==0.19.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - setuptools==68.2.2
      - setuptools-scm==7.1.0
      - shapely==1.8.5.post1
      - shellingham==1.5.4
      - shortuuid==1.0.11
      - sniffio==1.3.1
      - snowballstemmer==2.2.0
      - sphinx==7.1.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.6.2
      - starlette==0.44.0
      - superqt==0.6.7
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - tifffile==2023.7.10
      - tiffile==2018.10.18
      - tomli==2.0.1
      - tomli-w==1.0.0
      - tomlkit==0.13.3
      - toolz==0.12.0
      - topas2numpy==0.2.0
      - tornado==6.3.3
      - tqdm==4.67.1
      - traitlets==5.9.0
      - triangle==20250106
      - trove-classifiers==2025.5.9.12
      - typer==0.9.0
      - typing-extensions==4.8.0
      - urllib3==1.26.18
      - uvicorn==0.33.0
      - virtualenv==20.31.2
      - vispy==0.14.1
      - vizarr==0.0.1
      - wcwidth==0.2.6
      - websockets==12.0
      - widgetsnbextension==4.0.9
      - wrapt==1.15.0
      - xarray==0.16.2
      - xpublish==0.3.0
      - yarl==1.15.2
      - zarr==2.16.1
      - zipp==3.16.2
prefix: C:\Users\hamida\AppData\Local\anaconda3\envs\fly2p
